### PR TITLE
Fix resource leak in api.ValidateApikey

### PR DESCRIPTION
**Pull request by bvwells**
# GO SDK

## Tickets covered:
* None, but can create one if needed.

## What did you accomplish?
* Fix resource leak in api.ValidateApikey
* Handle error from `ioutil.ReadAll`
* Remove redundant if statement around range loop

## How to test new changes?
* `go test ./...`

## Extra Notes
* None

### CODE REVIEW

**Comment by mredolatti** [comment]
Hi @bvwells !

Thank you very much for reaching out and fixing the API token validation statement. Any reason for removing the check for the headers being nil? Nil is an acceptable value for a map: https://play.golang.org/p/fKWxQeT8hA-

Thanks again!

**Comment by bvwells** [comment]
Hi @mredolatti,
No problems! I removed the check on the nil map as it is not necessary to do this as the range keyword will deal with nil maps without the runtime crashing. See 

https://play.golang.org/p/EGBhay7lZLb

Hope this helps!
Ben

**Comment by mmelograno** [comment]
Proceeding to merge into development. Thanks @bvwells !

**Comment by bvwells** [comment]
Thanks for the merge @mmelograno!

**Pull request merged**
